services:

  order:
    build: ./Oreder Server
    ports:
      - "5002:5002"
    depends_on:
      - catalog
    volumes:
      - ./Oreder Server:/app
    
  frontend:
    build: ./Frontend Server
    ports:
      - "5000:5000"
    depends_on:
      - catalog
      - order
    volumes:
      - ./Frontend Server:/app
      
  catalog:
    build: ./Catalog Server
    ports:
      - "5001:5001"
    volumes:
      - ./Catalog Server:/app