version: '3'
services:
  frontend:
    image: frontend-server
    ports:
      - "5000:5000"
    depends_on:
      - catalog
      - order
  catalog:
    image: catalog-server
    ports:
      - "5001:5001"
  order:
    image: order-server
    ports:
      - "5002:5002"
    depends_on:
      - catalog