version: '1'

services:
  order:
    build: ./Order Server
    ports:
      - "5002:5002"
    depends_on:
      - catalog
      - catalog_replica
    volumes:
      - ./Order Server:/app
      
  order_replica:
    build: ./Order Replica Server
    ports:
      - "5004:5004"
    depends_on:
      - catalog
      - catalog_replica
    volumes:
      - ./Order Replica Server:/app
      
  frontend:
    build: ./Frontend Server
    ports:
      - "5000:5000"
    depends_on:
      - catalog
      - catalog_replica
      - order
      - order_replica
    volumes:
      - ./Frontend Server:/app
      
  catalog:
    build: ./Catalog Server
    ports:
      - "5001:5001"
    volumes:
      - ./Catalog Server:/app
      
  catalog_replica:
    build: ./Catalog Replica Server
    ports:
      - "5003:5003"
    volumes:
      - ./Catalog Replica Server:/app